// Seed data bundled at build time, regenerated by `npm run seed` from the
// archive repo. In demo mode this is the site's whole data layer; with a
// real backend it remains the roster/statistics baseline.
import rosterSeed from '../seed/roster.json';
import eventsSeed from '../seed/events.json';
import newsSeed from '../seed/news.json';
import serversSeed from '../seed/servers.json';

export interface Person {
  name: string;
  firstYear: number | null;
  games: string[];
  rank: string | null;
  steam_id64: string | null;
  entries: number;
}
export interface RosterEntry {
  person_name: string;
  person_key: string;
  steam_id64: string | null;
  game: string;
  rank_or_class: string | null;
  year: number | null;
  source: string;
  source_detail: string;
  notes: string | null;
}
export interface EventStat { year: number; game: string; events: number }
export interface NewsItem {
  title: string; body: string; author: string | null;
  date: string | null; site: string | null; truncated?: boolean;
}
export interface ServerInfo {
  server_key: string; game: string; name: string; address: string;
  online: boolean; players: number; max_players: number; map?: string;
}

export const people = (rosterSeed as { people: Person[] }).people;
export const rosterEntries = (rosterSeed as { entries: RosterEntry[] }).entries;
export const eventStats = eventsSeed as EventStat[];
export const news = newsSeed as NewsItem[];
export const servers = serversSeed as ServerInfo[];

export const THIS_YEAR = new Date().getFullYear();
export const yearsWithUs = (firstYear: number | null) =>
  firstYear ? THIS_YEAR - firstYear : null;

export const GAME_NAMES: Record<string, string> = {
  BG2: 'Battlegrounds 2', NW: 'Mount & Blade: Warband', MC: 'Minecraft',
  CSS: 'Counter-Strike: Source', CS16: 'Counter-Strike 1.6', CSGO: 'CS:GO',
  GMOD: "Garry's Mod", ARMA: 'ArmA 2', NS: 'North & South', RUST: 'Rust',
  GEN: 'Community',
};
