import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { FiArrowRight, FiShield, FiVolume2, FiVolumeX } from 'react-icons/fi';
import { BY_ID, PACKS, type Card, type Pack } from './catalogue';
import type { Receipt } from './store';
import { packSound, unlockPackAudio, mutePackAudio } from './sound';
export default function PackOpening({ receipt, renderCard, renderPack, done, busy }: { receipt: Receipt; renderCard: (card: Card) => ReactNode; renderPack: (pack: Pack) => ReactNode; done: () => void; busy: boolean }) {
  const [stage, setStage] = useState<'sealed' | 'tearing' | 'cards'>('sealed'); const [revealed, setRevealed] = useState<number[]>([]);
  const [sound, setSound] = useState(() => { try { return localStorage.getItem('rw-sound') !== 'off'; } catch { return false; } });
  const [motion, setMotion] = useState(() => !matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [last, setLast] = useState(-1); const timer = useRef<ReturnType<typeof setTimeout>>();
  const soundCurrent = useRef(sound); soundCurrent.current = sound;
  const pack = PACKS.find(p => p.name === receipt.name) || PACKS[0];
  useEffect(() => { const media = matchMedia('(prefers-reduced-motion: reduce)'); const change = () => setMotion(!media.matches); media.addEventListener('change', change); return () => { media.removeEventListener('change', change); clearTimeout(timer.current); }; }, []);
  function play(kind: Parameters<typeof packSound>[0]) { if (sound) { unlockPackAudio(); packSound(kind); } }
  function breakSeal() { play('seal'); if (!motion) { setStage('cards'); return; } setStage('tearing'); timer.current = setTimeout(() => { setStage('cards'); if (soundCurrent.current) packSound('deal'); }, 950); }
  function reveal(index: number) { if (revealed.includes(index)) return; play(BY_ID[receipt.cards[index].id].rarity); setLast(index); setRevealed(current => [...current, index]); }
  function revealAll() { const remaining = receipt.cards.filter((_, i) => !revealed.includes(i)); const best = remaining.some(c => BY_ID[c.id].rarity === 'legendary') ? 'legendary' : remaining.some(c => BY_ID[c.id].rarity === 'rare') ? 'rare' : 'common'; play(best); setRevealed(receipt.cards.map((_, i) => i)); setLast(-1); }
  const complete = revealed.length === receipt.cards.length; const lastCard = last >= 0 ? BY_ID[receipt.cards[last].id] : null;
  return <div className={`rw-opening ${motion ? 'motion' : 'still'} ${lastCard?.rarity === 'legendary' ? 'legendary-moment' : ''}`}>
    <div className="rw-opening-controls"><span className="rw-chip">{receipt.cards.length} cards · contents saved</span><button className="rw-text-button" aria-pressed={sound} onClick={() => { const next = !sound; setSound(next); if (next) unlockPackAudio(); else mutePackAudio(); try { localStorage.setItem('rw-sound', next ? 'on' : 'off'); } catch { /* Preference remains valid for this opening. */ } }}>{sound ? <FiVolume2 /> : <FiVolumeX />}{sound ? 'Sound on' : 'Sound off'}</button></div>
    {stage !== 'cards' ? <div className={`rw-seal-stage ${stage}`}><p className="rw-eyebrow">An issue from the regimental stores</p><div className="rw-sealed-pack">{renderPack(pack)}<div className="rw-seal-rays" /></div><h3>{stage === 'tearing' ? 'The seal gives way…' : 'Your reinforcements await.'}</h3><p>A fresh pack. A new place in your line.</p><button className="rw-button gold" disabled={stage === 'tearing'} onClick={breakSeal}>Break the seal <FiArrowRight /></button><button className="rw-text-button" onClick={() => { clearTimeout(timer.current); setStage('cards'); }}>Skip to the cards</button></div> : <>
      <div className="rw-reveal-announcement" aria-live="polite">{complete ? <><p className="rw-eyebrow">Issue complete</p><h3>{receipt.cards.filter(c => !c.duplicate).length} new cards. {receipt.cards.reduce((sum, c) => sum + c.supplies, 0)} supplies.</h3></> : lastCard ? <><p className={`rw-eyebrow ${lastCard.rarity}`}>{lastCard.rarity === 'legendary' ? 'A legend joins the ranks' : lastCard.rarity === 'rare' ? 'A veteran answers the call' : 'Reinforcements received'}</p><h3>{lastCard.name}</h3></> : <><p className="rw-eyebrow">The seal is broken</p><h3>Turn your first card.</h3></>}<p>{revealed.length} of {receipt.cards.length} revealed</p></div>
      <div className="rw-reveal-grid">{receipt.cards.map((received, index) => { const card = BY_ID[received.id]; const open = revealed.includes(index); return <div key={`${received.id}-${index}`} className={`rw-reveal-card ${open ? 'is-revealed ' + card.rarity : ''} ${last === index ? 'just-revealed' : ''}`} style={{ '--deal-delay': `${Math.min(index, 5) * 75}ms` } as CSSProperties}>{open ? <><div className="rw-flip-face">{renderCard(card)}</div>{card.rarity === 'legendary' && <div className="rw-sparks" aria-hidden="true">{Array.from({ length: 10 }, (_, i) => <i key={i} style={{ '--spark-x': `${(i % 5 - 2) * 40}px`, '--spark-y': `${-40 - Math.floor(i / 5) * 100}px`, '--spark-delay': `${i * 40}ms` } as CSSProperties} />)}</div>}<p className="rw-reveal-status">{received.duplicate ? `Duplicate · +${received.supplies} supplies` : 'New to your collection'}</p></> : <button className="rw-card-back" onClick={() => reveal(index)} aria-label={`Reveal card ${index + 1}`}><span>REGIMENT<br />WARS</span><FiShield /><small>Click to reveal</small></button>}</div>; })}</div>
      <div className="rw-actions">{complete ? <button className="rw-button gold" disabled={busy} onClick={done}>Build my deck <FiArrowRight /></button> : <><button className="rw-button gold" onClick={() => reveal(receipt.cards.findIndex((_, i) => !revealed.includes(i)))}>Reveal next card</button><button className="rw-button" onClick={revealAll}>Reveal all cards</button></>}<span className="rw-muted">Cards are saved. Take your time.</span></div>
    </>}
  </div>;
}
