import { FiCompass, FiFlag, FiPackage, FiShield } from 'react-icons/fi';
import type { CampaignSnapshot } from '../lib/campaign';

export default function CampaignHowTo({ state, openCamp }: { state: CampaignSnapshot; openCamp: () => void }) {
  if (state.expedition) return <ExpeditionGuide state={state} openCamp={openCamp} />;
  const p = state.project;
  const jobs = [
    ['Engineer: Gather', '+10 Materials, or the exact remaining need', 'Our Camp', 'Available now'],
    ['Engineer: Build', '+1 Construction Work', 'Our Camp', 'Available now'],
    ['Scout', '+2 Recon', 'Active operation', 'In development'],
    ['Escort Supplies', '+4 Supplies', 'Active operation', 'In development'],
    ['Prepare the Line', '+2 Readiness', 'Active operation', 'In development'],
  ];
  return <article className="lc-guide" aria-labelledby="lc-how-title">
    <header><p className="qm-eyebrow">Your field guide</p><h3 id="lc-how-title">How to Play</h3><p>One shared expedition. Everyone helps the same camp and campaign. You can make a useful contribution without spending a single Shilling.</p></header>
    <section className="lc-guide-goal"><FiFlag /><div><h4>The overall goal</h4><p>Prepare the company’s advance from camp to Fort Saint-Aubin. Choose routes and operation plans together, gather resources, build useful facilities, and eventually capture the fort. This is a fictional browser campaign with a pacing goal of roughly one month for 4–5 active members.</p><p><strong>Working now:</strong> the shared Field Kitchen, free Gather and Build orders, optional material funding, private receipts, cancellation refunds and automatic daily resolution. <strong>Still being built:</strong> operation play, ballots, random encounters and campaign cosmetics. The map lets you inspect those future destinations now.</p></div></section>
    <div className="lc-guide-steps">{[
      ['01', 'Join the expedition', 'Open Our Camp and join once to receive 3 free orders. Your order bank and history belong to this shared campaign.'],
      ['02', 'Choose useful work', 'Gather Materials or add Construction Work. Both tracks must be full. You can build while others gather; nobody needs to be online together.'],
      ['03', 'Review, then confirm', 'Each action shows the named project and exact useful output. Funding also shows the price, remaining limits and your resulting purse balance.'],
      ['04', 'Finish together', 'At the campaign-day boundary, fully prepared targets complete. Incomplete progress stays exactly where it is, ready for the next visit.'],
    ].map(([number, title, description]) => <section key={number}><span>{number}</span><h4>{title}</h4><p>{description}</p></section>)}</div>
    <section><h4>Your current mission: the Field Kitchen</h4><p>This Kitchen’s published goal is <strong>{p.requirements.materials} Materials and {p.requirements.work} Construction Work</strong>, frozen when it opened for {p.population} expected members. It can all be built with free orders. Later arrivals never make an active goal bigger.</p><p>After completion, the Kitchen raises Escort output from 4 to 5 Supplies in the following campaign cycle. That shared benefit becomes useful when operation play is added. Facility benefits last for the current campaign; your history stays.</p><button className="qm-button gold" onClick={openCamp}>Open Our Camp <FiPackage /></button></section>
    <section><h4>Free orders and what they do</h4><p>You receive <strong>3 orders when you first join</strong>, then <strong>3 more each campaign day</strong>, banked up to <strong>6</strong>. Leaving and rejoining does not give another starter grant. There are no paid refills, presence requirements or streak penalties.</p><div className="lc-help-table" tabIndex={0} role="region" aria-label="Free order reference"><table><caption>Each useful job costs one free order</caption><thead><tr><th scope="col">Job</th><th scope="col">Base output</th><th scope="col">Where</th><th scope="col">Availability</th></tr></thead><tbody>{jobs.map(([job, output, target, status]) => <tr key={job}><th scope="row">{job}</th><td>{output}</td><td>{target}</td><td>{status}</td></tr>)}</tbody></table></div><p>If only part of the output fits, the quote shows that exact amount. A full track accepts no more of that resource. If another member changes the target before you confirm, the quote is rejected and you keep your order. Review a fresh quote to continue.</p></section>
    <section><h4>Optional Shilling contributions</h4><p>Use the Shillings already available in your purse. Their earning source does not matter. The campaign never automatically withdraws savings from your Pay Chest or advances just because your balance increases elsewhere.</p><ul><li><strong>Building Materials, available now:</strong> 1 Shilling buys 1 Material for the named project. Funding can cover at most half of the original Materials requirement, currently {p.paidCap} Materials for this Kitchen. Every Material can also be gathered free, and all Construction Work requires free orders.</li><li><strong>Supply Packets, in development:</strong> 5 Shillings buys one indivisible packet of 2 Supplies for the active operation. Paid Supplies can cover at most 25% of its original Supply requirement. A packet that exceeds the remaining need or cap cannot be sold.</li><li><strong>Combined daily limit:</strong> 30 Shillings per member per campaign day across contribution types, including any unresolved funding reservations. This is a ceiling, never a recommended spend.</li></ul><p>You cannot buy orders, votes, Recon, Readiness, Construction Work or command authority. There are no repeatable Shilling prizes or real-money campaign-power purchases.</p></section>
    <section><h4>The campaign clock</h4><p>A new campaign day begins at <strong>05:00 America/Chicago</strong>, following daylight-saving changes. Our Camp shows the next cutoff in your local timezone. The same boundary grants banked orders and checks prepared targets.</p><p>At most one operation and one camp project resolve per cycle. Meeting the published requirements guarantees success. An incomplete target keeps its progress without punishment, decay or extra loss. A newly opened successor cannot also finish in that same cycle. Outage recovery does not simulate battles nobody played.</p></section>
    <section><h4>The map, plans and company decisions <span className="lc-wip">In development</span></h4><p>War Map shows the full route. Use the labeled map pieces or the location list to inspect each destination, its onward roads and the two plan options. A Prepared Assault and a Flank Approach ask for different resource mixes. Displayed future requirements are currently scaled for five participants.</p><p>Members will vote on the next location and plan, and the next facility. Each eligible campaign member gets one vote and may change it until the ballot closes. Wealth, company affiliation, titles and collectibles do not add voting weight.</p><p>The ballot closes when the current target completes. The winning eligible choice then opens with frozen requirements. Ties and no-vote outcomes use a published priority: Orchard, Windmill, Village, Supply Depot, Redoubt, then Fort; Prepared Assault before Flank Approach. Illegal or already captured options are skipped. Facility default priorities will be published with their ballot.</p><p>Only useful Scout, Escort and Prepare orders count toward an operation’s distinct-participant gate. Spending, voting and building the camp do not fill that gate. At the five-member planning size, four different members must help the operation through those free orders.</p></section>
    <section><h4>Camp facilities and lasting progress <span className="lc-wip">Beyond Kitchen: in development</span></h4><ul><li><strong>Field Kitchen:</strong> Escort provides 5 Supplies instead of 4.</li><li><strong>Engineer Workshop:</strong> Gather provides 12 Materials instead of 10.</li><li><strong>Signal Post:</strong> Scout provides 3 Recon instead of 2.</li></ul><p>Benefits begin in the cycle after completion and apply equally to everyone, including newcomers. One project is active at a time. Campaign history and earned cosmetics persist when a campaign ends, while these expedition bonuses end with the campaign.</p></section>
    <section><h4>Encounters along the road <span className="lc-wip">In development</span></h4><p>The planned encounter system adds a tabletop-adventure feel: washed-out roads, stranded wagons and unexplored outposts offer the company choices. These are internal campaign situations, unrelated to activity in any other game.</p><p>Encounter effects will be published before funding the affected objective. They will not secretly change an active funded goal, erase progress or introduce random failure after all published requirements are met. The examples on War Map are concepts; encounter rules and month-long pacing still need testing.</p></section>
    <section><h4>Receipts, refunds and connection trouble</h4><ul><li><strong>Committed:</strong> your Shillings have paid for useful progress on this specific target.</li><li><strong>Consumed:</strong> the target completed and used that commitment.</li><li><strong>Refunded:</strong> an authorized moderator canceled an unfinished target or closed the unfinished campaign. The original amount returned once to its original owner. The refund links back to the original ledger receipt.</li><li><strong>Pending:</strong> confirmation has not arrived. Use Reconcile saved request. It checks the original request instead of charging again. Refreshing or reopening the page preserves that recovery request.</li><li><strong>Rejected:</strong> the current action was not accepted. Review the explanation and request a new quote. A stale or useless order spends nothing.</li></ul><p>Members cannot retract active shared funding at will. Canceling requires an authorized moderator and a reason; funds cannot be redirected or withdrawn into a moderator’s purse. Refunded amounts still count against their original day’s limit. Refunds are not new earnings. Completed commitments remain consumed if the campaign later closes.</p></section>
    <section><h4>Finding your way around</h4><div className="lc-help-surfaces"><p><FiCompass /><strong>War Map:</strong> inspect the whole expedition and its future decisions. Map gameplay is clearly marked as work in progress.</p><p><FiPackage /><strong>Our Camp:</strong> see the saved Kitchen progress, spend free orders, review optional funding, and check the next resolution.</p><p><FiShield /><strong>My Service:</strong> privately review your useful campaign orders and readable contribution receipts. Cosmetics and three pinned campaign highlights will be added later.</p><p><FiFlag /><strong>Dispatches:</strong> read the campaign’s confirmed completion and cancellation reports. Reports stay on the website.</p></div><p>Private balances and exact individual contributions stay private. Campaign cosmetics are game achievements, separate from personnel ranks and real service medals. Your actions here do not depend on calendars, attendance, game servers, Discord activity or card matches.</p></section>
  </article>;
}

function ExpeditionGuide({ state, openCamp }: { state: CampaignSnapshot; openCamp: () => void }) {
  return <article className="lc-guide" aria-labelledby="lc-how-title">
    <header><p className="qm-eyebrow">Your field guide</p><h3 id="lc-how-title">How to Play</h3><p>One company. One shared expedition. Everyone helps the same campaign, and every target can be completed without spending Shillings.</p></header>
    <section className="lc-guide-goal"><FiFlag /><div><h4>The overall goal</h4><p>Advance from Camp through the valley and capture Fort Saint-Aubin. Prepare each location, decide the route together, overcome encounters, and improve the camp. The company wins when the fort’s final phase is secured.</p><p><strong>Playable now:</strong> all seven destinations, three phases at each, all five free jobs, route and facility votes, random road encounters, supply packets, three camp facilities, shared progress and the campaign ending. <strong>Work in progress:</strong> more encounter stories, additional world detail and campaign cosmetics/showcase rewards.</p></div></section>
    <div className="lc-guide-steps">{[['01', 'Join the company', 'Join in Operations or Our Camp. You receive 3 starter orders once. Everyone contributes to the same saved state.'], ['02', 'Help the advance', 'Scout, Escort or Prepare the Line on Operations, or Gather and Build in Our Camp. Review the exact useful output, then confirm.'], ['03', 'Have your say', 'Vote on the road encounter, next destination and plan, and next facility. You can change an open vote.'], ['04', 'Watch the world respond', 'Confirmed actions animate on the shared board. Prepared phases resolve at the daily cutoff, and the company advances after securing a location.']].map(([n, title, body]) => <section key={n}><span>{n}</span><h4>{title}</h4><p>{body}</p></section>)}</div>
    <section><h4>Moving around the living board</h4><p>On War Map, drag to move the view, use the wheel or zoom buttons to get closer, and pinch with two fingers on touch devices. The turn buttons rotate the table; Reset restores the overview. Keyboard controls are available when the map is focused: arrows to pan, + and - to zoom, and 0 to reset.</p><p>The company standard marks where we are. The highlighted destination is our current objective. The route legend distinguishes secured roads, the active advance, available branches and unexplored routes. Click any label or use the location list to inspect a destination.</p><p>Confirmed work sends scouts, supplies and other pieces across the board for everyone watching. The board checks shared progress every 4 seconds while visible. A vote animates its destination, but the company moves only when the resolved campaign state advances. Reloads and payment retries do not replay old celebrations.</p><p>Use <strong>Pause motion</strong> to stop ambient and action animations. The interface also respects your device’s reduced-motion preference. Reading, voting, dragging and zooming remain available.</p></section>
    <section><h4>Orders: the complete free path</h4><p>You get <strong>3 orders on first join</strong>, then <strong>3 every campaign day</strong>, banked up to <strong>6</strong>. All five jobs cost one order. You do not need to be online together. Rejoining does not grant another starter bank, and there are no paid refills or streak penalties.</p><div className="lc-help-table" tabIndex={0} role="region" aria-label="Free order reference"><table><caption>Base output before shared facilities</caption><thead><tr><th scope="col">Job</th><th scope="col">Output</th><th scope="col">Where</th><th scope="col">Facility benefit</th></tr></thead><tbody>{[['Scout', '2 Recon', 'Operations', 'Signal Post: 3 Recon'], ['Escort Supplies', '4 Supplies', 'Operations', 'Field Kitchen: 5 Supplies'], ['Prepare the Line', '2 Readiness', 'Operations', 'None'], ['Engineer: Gather', '10 Materials', 'Our Camp', 'Workshop: 12 Materials'], ['Engineer: Build', '1 Construction Work', 'Our Camp', 'None']].map(([job, output, where, bonus]) => <tr key={job}><th scope="row">{job}</th><td>{output}</td><td>{where}</td><td>{bonus}</td></tr>)}</tbody></table></div><p>A quote shows only useful output. If 1 Recon remains, your Scout quote provides 1. Full tracks accept no further work. If another member changes the target or your purse before confirmation, request a fresh quote; a rejected action spends nothing.</p></section>
    <section><h4>Three phases at every destination</h4><p>Each location has <strong>Approach, Secure and Hold</strong> phases. Each phase publishes its Recon, Supplies and Readiness requirements when it opens. Fill all three tracks and meet the distinct-member requirement before the next cutoff. After Hold, the location becomes ours and the winning legal next route opens.</p><p>At the current five-member planning size, <strong>four different members</strong> must contribute useful Scout, Escort or Prepare orders in each phase. Spending, voting and camp work do not count toward this gate. No one can purchase a place in the participant count.</p><p>The game reserves at least one useful unit for each required member who has not helped yet. Your quote may be smaller, or ask you to wait for the company, so early contributors cannot use up the last chance for someone else to participate. Funding and encounters respect the same reserve.</p><p>Each new phase is a separate published objective with its own frozen requirements and funding cap. Completing a location does not automatically complete its successor. Work never decays when people are away. Using most daily orders, 4–5 members can aim for roughly a month. Less frequent visits take longer because the bank holds six orders; there is no expiry or penalty for taking your time.</p></section>
    <section><h4>The campaign clock</h4><p>A new campaign day starts at <strong>05:00 America/Chicago</strong>, following daylight-saving changes. The camp displays your local next cutoff. Orders accrue at this boundary, an open encounter resolves, and prepared targets are checked.</p><p>At most one operation phase and one camp facility complete per cycle. An incomplete phase stays exactly where it is. Success is guaranteed once its published requirements and member gate are satisfied; there is no hidden failure roll. Outage recovery never runs a chain of unseen victories.</p></section>
    <section><h4>Route and facility votes</h4><p>Each joined, eligible member has one vote in each open ballot. Wealth and collectibles add no weight. Route voting includes a destination and either Prepared Assault or Flank Approach, which ask for different resource mixes. Only legal choices appear. Votes may change until the current location’s final phase completes.</p><p>Ties or no votes use this published priority: Orchard, Windmill, Village, Supply Depot, Redoubt, Fort. Prepared Assault precedes Flank Approach. Captured or unreachable choices are skipped. The fort requires the Redoubt. Optional side routes remain choices while legal.</p><p>The camp ballot closes when the current facility completes. Its default order is Engineer Workshop, then Signal Post. All votes remain private to your account except public totals.</p></section>
    <section><h4>Random encounters and the saved die</h4><p>Each phase draws an internal road encounter once, such as a washed-out route, a stranded wagon or an abandoned outpost. Read both options and their effects before voting. The company’s majority choice resolves at the next cutoff; tied or empty ballots use the first listed option.</p><p>A d20 result is saved with the encounter. Refreshing never changes it. The resolved card reveals the roll, decision and outcome. Effects add bounded useful progress according to the published terms. They never secretly increase a funded requirement, erase completed work or turn a fully prepared phase into a loss.</p></section>
    <section><h4>Optional Shilling support</h4><ul><li><strong>Materials:</strong> 1 Shilling buys 1 Material for the current camp project. At most 50% of its original Materials can be paid for. Work always requires free Build orders.</li><li><strong>Supply packets:</strong> 5 Shillings buys 2 Supplies for the current operation phase. At most 25% of its original Supplies can be paid for, rounded down to whole packets. A packet that cannot fully fit is rejected.</li><li><strong>Shared daily ceiling:</strong> at most 30 Shillings per member across both kinds of funding in the same campaign day. Refunded commitments still count against their original day.</li></ul><p>Review the exact output, named target, price, remaining limits and resulting purse before confirming. Your existing Shillings are eligible regardless of how you earned them. Pay Chest savings are never withdrawn automatically. No paid orders, votes, Recon, Readiness or command authority exist.</p></section>
    <section><h4>The camp and territory benefits</h4><p>Field Kitchen improves Escort from 4 to 5 Supplies. Engineer Workshop improves Gather from 10 to 12 Materials. Signal Post improves Scout from 2 to 3 Recon. Benefits begin in the cycle after completion, apply equally to newcomers and expire when this campaign ends.</p><p>The Orchard provides 4 starting Supplies, the Windmill provides 2 starting Recon, and the Supply Depot provides 8 starting Supplies. Matching territory benefits use the highest value, so the Depot replaces the Orchard supply benefit rather than adding to it.</p><p>Your current {state.project.name} needs {state.project.requirements.materials} Materials and {state.project.requirements.work} Work, frozen for {state.project.population} expected members when it opened. Existing progress and requirements were kept during the expedition upgrade. Future targets are planned for five.</p><button className="qm-button gold" onClick={openCamp}>Open Our Camp <FiPackage /></button></section>
    <section><h4>Receipts, refunds and connection recovery</h4><ul><li><strong>Committed:</strong> payment and useful target progress were saved together.</li><li><strong>Consumed:</strong> the target completed and used its commitment.</li><li><strong>Refunded:</strong> an unfinished target was canceled, or the campaign closed with unused commitments. Funds returned exactly once to their original owners, linked to the original ledger receipt.</li><li><strong>Pending:</strong> confirmation has not arrived. Reconcile saved request checks the same action and cannot charge twice. Reopening the page preserves it.</li><li><strong>Rejected:</strong> the action was not accepted. Read the reason, refresh and request a new quote.</li></ul><p>Members cannot retract active funding at will. Moderators must supply a reason to cancel an unfinished target. Finished commitments are never refunded again. Refunds do not count as earnings. Victory preserves the journey and reconciles any unfinished commitments; it grants no repeatable Shilling payout.</p></section>
    <section><h4>Your records and what comes next</h4><p>My Service privately records your useful orders and readable contribution receipts. Dispatches records shared encounters, facilities, phase results and the campaign ending. Public activity shows what happened without exposing individual balances or exact paid contributions.</p><p>Campaign cosmetics and three pinned showcase highlights are still in development. These are game achievements, separate from real personnel ranks and medals. More map detail and encounter variety will be completed as the campaign develops.</p><p>This game stands on its own. Calendar events, attendance, Discord activity, game-server results and card matches never advance the expedition.</p></section>
  </article>;
}
