import { useState } from 'react';
import { FiArrowRight, FiCheck, FiCompass, FiFlag, FiPackage, FiShield, FiUsers } from 'react-icons/fi';
import type { CampaignCommand, CampaignSnapshot } from '../lib/campaign';

type Props = { state: CampaignSnapshot; disabled: boolean; hasQuote: boolean; command: (action: CampaignCommand['action'], args?: Record<string, string>) => void; review: (kind: 'order' | 'materials' | 'supplies', job?: string, targetId?: string, amount?: number) => void };
export const planName = (id: string) => id === 'flank_approach' ? 'Flank Approach' : 'Prepared Assault';

export default function CampaignOperations({ state, disabled, hasQuote, command, review }: Props) {
  const [packets, setPackets] = useState('1');
  const e = state.expedition;
  if (!e) return <section className="lc-records"><h3>The expedition is being prepared</h3><p>Operation play will appear when this campaign is upgraded.</p></section>;
  const o = e.operation;
  const blocked = disabled || !state.member.joined || hasQuote || e.victory;
  if (e.victory) return <section className="lc-victory"><FiFlag /><p className="qm-eyebrow">The company has reached its destination</p><h3>Saint-Aubin is ours.</h3><p>The fort is secured. Every useful order, every completed facility and the company’s journey remain in your campaign record.</p><p>There are no repeatable Shilling prizes. Your shared achievement is the expedition itself.</p><span className="lc-status completed">Campaign complete</span></section>;
  if (!o) return <section className="lc-records"><h3>Awaiting the next operation</h3><p>Check the company’s dispatches for the latest orders.</p></section>;
  const ready = o.recon >= o.requirements.recon && o.supplies >= o.requirements.supplies && o.readiness >= o.requirements.readiness && o.participants >= o.participantGate;
  return <div className="lc-expedition-play">
    <div className="lc-operation-heading"><div><p className="qm-eyebrow">Current operation · {planName(o.plan)}</p><h3>{o.name}</h3><p>{ready ? 'The company is ready. This phase resolves at the next campaign cutoff.' : 'Prepare all three tracks and bring the company together to secure this phase.'}</p></div><span className={`lc-status ${ready ? 'completed' : ''}`}>{o.status === 'cancelled' ? 'Operation canceled' : ready ? 'Ready for resolution' : `Phase ${o.phase} of 3`}</span></div>
    <ol className="lc-phase-track" aria-label="Operation phases">{e.phaseNames.map((name, i) => <li key={name} className={i + 1 === o.phase ? 'current' : i + 1 < o.phase ? 'complete' : ''} aria-current={i + 1 === o.phase ? 'step' : undefined}><span>{i + 1 < o.phase ? <FiCheck /> : i + 1}</span><strong>{name}</strong></li>)}</ol>
    <div className="lc-operation-layout"><section className="lc-operation-work"><h4>{o.phaseName}: prepare the advance</h4><div className="lc-resource-tracks">{([['recon', 'Recon', FiCompass], ['supplies', 'Supplies', FiPackage], ['readiness', 'Readiness', FiShield]] as const).map(([key, label, Icon]) => <div className="lc-progress" key={key}><div><label htmlFor={`operation-${key}`}><Icon /> {label}</label><strong>{o[key]}<small> / {o.requirements[key]}</small></strong></div><progress id={`operation-${key}`} value={o[key]} max={o.requirements[key]} /><small>{key === 'supplies' ? `${o.paidSupplies} funded · ${o.paidCap} maximum paid` : 'Built with free campaign orders'}</small></div>)}</div>
      <div className={`lc-participants ${o.participants >= o.participantGate ? 'ready' : ''}`}><FiUsers /><div><strong>{o.participants} / {o.participantGate} different members have helped</strong><p>Scout, Escort and Prepare orders count. Funding and votes do not fill this requirement.</p></div><div aria-hidden="true">{Array.from({ length: o.participantGate }, (_, i) => <i key={i} className={i < o.participants ? 'filled' : ''} />)}</div></div>
      {!state.member.joined && <button className="qm-button gold" disabled={disabled} onClick={() => command('join')}>Join the expedition <FiArrowRight /></button>}
      <div className="lc-operation-jobs">{([['scout', 'Scout the approach', 'recon', FiCompass], ['escort', 'Escort supplies', 'supplies', FiPackage], ['prepare', 'Prepare the line', 'readiness', FiShield]] as const).map(([job, name, resource, Icon]) => <button key={job} className="lc-job" disabled={blocked || !state.member.orders || o.status !== 'active' || o[resource] >= o.requirements[resource]} onClick={() => review('order', job, o.id)}><Icon /><span><strong>{name}</strong><small>Review useful {resource} before confirming</small></span><b>1 order</b></button>)}</div><p className="lc-free-note">{state.member.orders} free orders available. All three phases can be completed without spending Shillings.</p>
    </section><aside className="lc-funding"><p className="qm-eyebrow">Optional shared provisions</p><h4>Send supply packets</h4><p>One packet costs 5 Shillings and provides 2 Supplies. Packets cannot be split. The same 30-Shilling daily limit covers supplies and building materials.</p><label htmlFor="lc-packets">Number of packets</label><div className="lc-amount-row"><input id="lc-packets" type="number" min="1" max="6" step="1" value={packets} disabled={blocked} onChange={event => setPackets(event.target.value)} /><span>packets</span></div><button className="qm-button" disabled={blocked || o.status !== 'active' || !/^[1-6]$/.test(packets)} onClick={() => review('supplies', undefined, o.id, Number(packets))}>Review {Number(packets) > 0 ? Number(packets) * 5 : 0} Shillings <FiArrowRight /></button><dl><div><dt>Available purse</dt><dd>{state.member.availableBalance}</dd></div><div><dt>Accepted today</dt><dd>{state.member.acceptedToday} / {state.member.dailyCap}</dd></div><div><dt>Paid supply allowance</dt><dd>{o.paidSupplies} / {o.paidCap}</dd></div></dl><small>At most 25% of this phase’s original Supplies can be funded. Recon and Readiness always require free orders.</small></aside></div>
    {e.encounter && <section className="lc-road-encounter" aria-label="Road encounter"><div className="lc-encounter-art" role="img" aria-label="A supply wagon and expedition halted along a misty woodland road" /><div className="lc-encounter-content"><p className="qm-eyebrow">An encounter on the road · {e.encounter.status === 'open' ? 'Company decision' : 'Resolved'}</p><h3>{e.encounter.title}</h3><p>{e.encounter.description}</p>{e.encounter.status === 'open' ? <><p className="lc-plan-note">One vote each. Change your vote until the next campaign cutoff. Ties follow the order shown. The outcome is drawn once and saved; refreshing never rerolls it.</p><div className="lc-encounter-options">{e.encounter.options.map(option => <button key={option.id} className={e.encounter?.ownVote === option.id ? 'chosen' : ''} aria-pressed={e.encounter?.ownVote === option.id} disabled={blocked} onClick={() => command('vote_encounter', { optionId: option.id })}><span><strong>{option.label}</strong><small>{option.description}</small></span><b>{option.votes} vote{option.votes === 1 ? '' : 's'}</b>{e.encounter?.ownVote === option.id && <FiCheck />}</button>)}</div></> : <div className="lc-encounter-outcome"><span className="lc-die" aria-label={`Saved d20 roll: ${e.encounter.roll}`}>{e.encounter.roll ?? '✓'}</span><div><strong>The company’s decision stands.</strong><p>{e.encounter.outcome}</p></div></div>}</div></section>}
    <CampaignCouncil state={state} disabled={blocked} command={command} />
  </div>;
}

export function CampaignCouncil({ state, disabled, command }: Pick<Props, 'state' | 'disabled' | 'command'>) {
  const e = state.expedition; if (!e || e.victory) return null;
  return <section className="lc-council" aria-label="Company decisions"><div><p className="qm-eyebrow">Everyone has a say</p><h3>The company council</h3><p>One member, one vote. Spending adds no weight. Votes remain changeable until the active target completes.</p></div><div className="lc-ballot-grid"><section><h4>Our next destination</h4><p>The route ballot closes when all three phases at {e.operation?.name ?? 'the current location'} are complete. Only reachable destinations appear.</p>{e.routeBallot.options.length ? <div className="lc-ballot-options">{e.routeBallot.options.map(option => { const selected = e.routeBallot.own?.nodeId === option.nodeId && e.routeBallot.own?.plan === option.plan; return <button key={`${option.nodeId}-${option.plan}`} disabled={disabled} aria-pressed={selected} onClick={() => command('vote_route', { nodeId: option.nodeId, plan: option.plan })}><span><strong>{option.name}</strong><small>{planName(option.plan)}</small></span><b>{option.votes}</b>{selected && <FiCheck />}</button>; })}</div> : <p>No further route ballot is needed for this objective.</p>}<small>Ties: Orchard, Windmill, Village, Supply Depot, Redoubt, Fort. Prepared Assault before Flank Approach. Unavailable choices are skipped.</small></section><section><h4>Our next camp facility</h4><p>Choose what follows the current project. Its requirements freeze when it opens.</p>{e.projectBallot.options.length ? <div className="lc-ballot-options">{e.projectBallot.options.map(option => <button key={option.blueprint} disabled={disabled} aria-pressed={e.projectBallot.own === option.blueprint} onClick={() => command('vote_project', { blueprint: option.blueprint })}><span><strong>{option.name}</strong><small>{option.blueprint === 'workshop' ? 'Gather 12 Materials per order' : 'Scout 3 Recon per order'}</small></span><b>{option.votes}</b>{e.projectBallot.own === option.blueprint && <FiCheck />}</button>)}</div> : <p>All remaining facilities are already built or under construction.</p>}<small>Ties: Engineer Workshop, then Signal Post. Benefits begin in the cycle after completion.</small><div className="lc-built-facilities">{e.facilities.map(facility => <span key={facility.blueprint}><FiCheck /> {facility.name} · {facility.benefitActive ? 'Active' : 'Ready next cycle'}</span>)}</div></section></div></section>;
}
