import { useCallback, useEffect, useRef, useState } from 'react';
import { FiArrowRight, FiCheck, FiClock, FiFlag, FiTool, FiPackage, FiRefreshCw, FiShield } from 'react-icons/fi';
import { campaignAct, campaignQuote, campaignRead, CampaignRequestError, type CampaignCommand, type CampaignQuote, type CampaignSnapshot } from '../lib/campaign';
import '../living-campaign.css';
import CampaignMap from './CampaignMap';
import CampaignHowTo from './CampaignHowTo';
import CampaignOperations, { planName } from './CampaignOperations';
import '../campaign-expedition.css';

const date = (value: string) => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZoneName: 'short' });
function CampScene({ complete, started, name }: { complete: boolean; started: boolean; name: string }) {
  return <svg className={`lc-scene ${complete ? 'complete' : ''}`} viewBox="0 0 820 350" role="img" aria-labelledby="camp-scene-title">
    <title id="camp-scene-title">Shared field camp: {name}: {complete ? 'complete' : started ? 'under construction' : 'blueprint ready'}</title>
    <defs><pattern id="camp-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="currentColor" strokeWidth=".35" /></pattern><linearGradient id="camp-ground" x2="0" y2="1"><stop stopColor="#30382c" /><stop offset="1" stopColor="#161c18" /></linearGradient></defs>
    <rect width="820" height="350" fill="url(#camp-ground)" /><rect width="820" height="350" fill="url(#camp-grid)" opacity=".3" />
    <path d="M0 236Q110 150 214 219T426 194T644 206T820 153V350H0Z" fill="#414938" opacity=".4" />
    <path d="M0 282Q250 247 376 301T820 265" fill="none" stroke="#928569" opacity=".35" strokeWidth="25" />
    <g stroke="#a69976" strokeWidth="2" opacity=".62"><path d="M60 246L123 160L193 246ZM123 160V246M189 246L240 182L296 246ZM240 182V246" fill="#555941" /><path d="M663 225L710 160L775 225ZM710 160V225" fill="#555941" /></g>
    <g stroke={complete ? '#dcc490' : '#a99d75'} strokeWidth="2" strokeDasharray={started || complete ? undefined : '7 5'}>
      <path d="M336 267V173L461 109L584 176V268Z" fill={started || complete ? '#56563c' : '#252e25'} />
      <path d="M312 181L459 97L608 182L580 190L459 129L337 192Z" fill={complete ? '#827452' : '#3b4434'} />
      <path d="M364 265V189H408V265M488 192H550V228H488Z" fill="#202a22" />
      <path d="M526 136V77H551V151" fill={complete ? '#948565' : '#353e2e'} />
      {complete && <><path d="M532 64Q517 42 538 25M547 65Q567 38 550 13" fill="none" opacity=".4" /><path d="M415 267H494" strokeWidth="7" /></>}
      {!complete && started && <path d="M322 267V191M595 266V191M315 221H606M344 270L576 190" fill="none" />}
    </g>
    <g stroke="#c4ab71" strokeWidth="2"><path d="M633 260V105" /><path d="M634 106H691L681 125L691 143H634Z" fill="#713e35" /></g>
    <g fill="#ddcb9a" fontFamily="Georgia, serif"><text x="36" y="45" fontSize="14" letterSpacing="3">THE SHARED FIELD CAMP</text><text x="459" y="311" textAnchor="middle" fontSize="20">{name}</text><text x="784" y="325" textAnchor="end" fontSize="11" letterSpacing="2">SECOND TO NONE</text></g>
  </svg>;
}

export default function LivingCampaign({ demo, memberId, refreshWallet }: { demo: boolean; memberId: string; refreshWallet: () => Promise<void> }) {
  const storageKey = `living-campaign:pending:${memberId}`;
  const [state, setState] = useState<CampaignSnapshot | null>(null);
  const [quote, setQuote] = useState<CampaignQuote | null>(null);
  const [amount, setAmount] = useState('10'); const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false); const lock = useRef(false); const sequence = useRef(0);
  const [notice, setNotice] = useState(''); const [error, setError] = useState(false); const [reconnecting, setReconnecting] = useState(false);
  const [pulse, setPulse] = useState(false); const [localView, setLocalView] = useState<'map' | 'operation' | 'camp' | 'service' | 'dispatches' | 'help'>('map');
  const [motion, setMotion] = useState(() => { try { return !window.matchMedia('(prefers-reduced-motion: reduce)').matches && localStorage.getItem('living-campaign:motion') !== 'off'; } catch { return false; } });
  const [liveMessage, setLiveMessage] = useState<{id: string; label: string; kind: string} | null>(null);
  const seenActivity = useRef<Set<string> | null>(null);
  const [pending, setPending] = useState<CampaignCommand | null>(() => { try { const value = localStorage.getItem(storageKey); return value ? JSON.parse(value) : null; } catch { return null; } });
  const quotePanel = useRef<HTMLDivElement>(null);
  const clearSaved = () => { try { localStorage.removeItem(storageKey); } catch { /* A leftover key safely replays the original receipt. */ } };
  const load = useCallback(async (silent = false) => {
    if (lock.current) return;
    const epoch = ++sequence.current;
    try { const next = await campaignRead(demo); if (epoch === sequence.current) { setState(next); setReconnecting(false); if (!silent) { setNotice(''); setError(false); } } }
    catch (e) { if (epoch === sequence.current) { setReconnecting(true); setNotice(e instanceof Error ? e.message : 'The board is unavailable.'); setError(true); } }
  }, [demo]);
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (!document.hidden) void load(true); }, 4000); return () => { window.clearInterval(timer); sequence.current++; }; }, [load]);
  useEffect(() => {
    const events = state?.expedition?.activity;
    if (!events) return;
    if (!seenActivity.current) { seenActivity.current = new Set(events.map(event => event.id)); return; }
    const fresh = events.filter(event => !seenActivity.current!.has(event.id));
    events.forEach(event => seenActivity.current!.add(event.id));
    if (seenActivity.current.size > 1000) seenActivity.current = new Set(events.map(event => event.id));
    if (fresh.length) { const newest = [...fresh].sort((a, b) => a.at.localeCompare(b.at)).at(-1)!; setLiveMessage(newest); setPulse(true); }
  }, [state?.expedition?.activity]);
  useEffect(() => { if (!liveMessage) return; const timer = window.setTimeout(() => setLiveMessage(null), 5200); return () => window.clearTimeout(timer); }, [liveMessage]);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const changed = () => { if (media.matches) setMotion(false); }; media.addEventListener('change', changed); return () => media.removeEventListener('change', changed); }, []);
  useEffect(() => { if (quote) quotePanel.current?.focus(); }, [quote]);
  useEffect(() => { if (!pulse) return; const timer = window.setTimeout(() => setPulse(false), 800); return () => window.clearTimeout(timer); }, [pulse]);
  const execute = async (command: CampaignCommand) => {
    if (lock.current) return; lock.current = true; sequence.current++; setBusy(true); setError(false); setPulse(false); setNotice('Settling your request with the campaign ledger…');
    try {
      // Only the original request identity is retained, never a cached balance or success.
      localStorage.setItem(storageKey, JSON.stringify(command)); setPending(command);
      const result = await campaignAct(demo, command);
      setState(result.snapshot); setNotice(result.message); setQuote(null); setPending(null); clearSaved(); setReconnecting(false);
      if (!result.replayed) setPulse(true);
      if (!result.replayed && localView === 'map') requestAnimationFrame(() => document.querySelector('.lc-map-frame')?.scrollIntoView({ block: 'center', behavior: motion && !window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'smooth' : 'auto' }));
      void refreshWallet();
    } catch (e) {
      const uncertain = e instanceof CampaignRequestError && e.pending;
      setError(true); setNotice(uncertain ? 'Pending confirmation. Your request may already have completed. Reconcile the saved request to retrieve its receipt.' : e instanceof Error ? e.message : 'The request was rejected.');
      if (!uncertain) { setPending(null); clearSaved(); setQuote(null); }
    } finally { lock.current = false; setBusy(false); }
  };
  const command = (action: CampaignCommand['action'], args: Record<string, string> = {}) => void execute({ action, args, requestId: crypto.randomUUID() });
  const review = async (kind: 'order' | 'materials' | 'supplies', job?: string, targetId?: string, quantity?: number) => {
    if (!state || lock.current || pending) return; lock.current = true; sequence.current++; setBusy(true); setError(false); setNotice('Loading the exact useful output…');
    try { setQuote(await campaignQuote(demo, { kind, targetId: targetId ?? state.project.id, ...(kind === 'order' ? { job } : { amount: quantity ?? Number(amount) }) })); setNotice('Review your quote before confirming.'); }
    catch (e) { setQuote(null); setError(true); setNotice(e instanceof Error ? e.message : 'The quote could not be loaded.'); }
    finally { lock.current = false; setBusy(false); }
  };
  if (!state) return <section className="lc-board lc-loading"><p className="qm-eyebrow">Living Campaign</p><h2>{reconnecting ? 'The board is unavailable.' : 'Opening the shared field camp…'}</h2><p role={reconnecting ? 'alert' : 'status'}>{notice || 'Loading saved campaign progress and your free orders.'}</p>{reconnecting && <button className="qm-button" onClick={() => void load()}>Open board again</button>}</section>;
  const { project: p, member: m, campaign: c, expedition: expedition } = state;
  const operation = expedition?.operation;
  const ready = p.materials === p.requirements.materials && p.work === p.requirements.work;
  const disabled = busy || Boolean(pending) || m.frozen || reconnecting || c.status !== 'active';
  const actionable = !disabled && m.joined && p.status === 'active';
  const mapActions = expedition && !expedition.victory && <section className="lc-map-orders" aria-label="Orders from the war map"><div><p className="qm-eyebrow">Give an order. Watch it reach the company.</p><strong>{operation?.name} · {m.orders} free orders available</strong></div>{!m.joined ? <button className="qm-button gold" disabled={disabled} onClick={() => command('join')}>Join the expedition <FiArrowRight /></button> : <div className="lc-map-order-buttons">{([['scout', 'Scout', 'recon'], ['escort', 'Escort', 'supplies'], ['prepare', 'Prepare', 'readiness']] as const).map(([job, label, resource]) => <button className="qm-button" key={job} disabled={disabled || Boolean(quote) || !m.orders || !operation || operation.status !== 'active' || operation[resource] >= operation.requirements[resource]} onClick={() => void review('order', job, operation?.id)}>{label}<small>1 order</small></button>)}<button className="qm-button" disabled={disabled || Boolean(quote) || !operation || operation.status !== 'active'} onClick={() => void review('supplies', undefined, operation?.id, 1)}>Send supplies<small>Review 5 Shillings</small></button></div>}{expedition.encounter?.status === 'open' && <div className="lc-map-road-choice"><span>{expedition.encounter.title}</span>{expedition.encounter.options.map(option => <button key={option.id} className="qm-text-button" disabled={disabled || !m.joined || Boolean(quote)} aria-pressed={expedition.encounter?.ownVote === option.id} onClick={() => command('vote_encounter', { optionId: option.id })}><span>{option.label}<small>{option.description}</small></span><FiCheck /></button>)}</div>}<button className="qm-text-button" onClick={() => setLocalView('operation')}>Full mission &amp; route decisions <FiArrowRight /></button></section>;
  const status = c.status === 'closed' ? 'Campaign closed' : p.status === 'completed' ? 'Facility complete' : p.status === 'cancelled' ? 'Project canceled' : ready ? 'Ready for resolution' : p.materials || p.work ? 'Construction in progress' : 'Blueprint ready';
  return <section className={`lc-board ${pulse ? 'lc-confirmed' : ''} ${motion ? 'lc-motion-on' : 'lc-motion-off'} ${expedition?.victory ? 'lc-campaign-victory' : ''}`} aria-label="Living Campaign board" aria-busy={busy}>
    <header className="lc-heading lc-hero"><div><p className="qm-eyebrow">One campaign · One camp · Built together</p><h2>Living Campaign</h2><p>{c.title} <span className="lc-edition">{expedition ? 'Work in progress · Playable expedition' : 'Pilot 0.3 · Milestone 1'}</span></p></div><div className="lc-sync"><button className="qm-text-button lc-motion-toggle" aria-pressed={motion} onClick={() => setMotion(value => { const next = !value; try { localStorage.setItem('living-campaign:motion', next ? 'on' : 'off'); } catch { /* Preference only. */ } return next; })}>{motion ? 'Pause motion' : 'Enable motion'}</button><span><i />{reconnecting ? 'Reconnecting' : 'Shared board · live updates every 4s'}</span><button className="qm-text-button" disabled={busy} onClick={() => void load()}><FiRefreshCw /> Refresh board</button></div></header>
    {state.preview && <p className="lc-preview"><FiShield /> Isolated staging · persistent test accounts and test Shillings. Production campaign is off.</p>}
    <section className="lc-mission" aria-label="Mission brief"><div><p className="qm-eyebrow">Mission brief</p><h3>{expedition?.victory ? 'Saint-Aubin secured. The road is ours.' : 'Establish camp. Open the road. Reach Saint-Aubin.'}</h3><p>Our company is preparing a shared expedition through the valley. Build a dependable camp, choose the way forward together, and capture Fort Saint-Aubin.</p></div><aside><strong>{operation && !expedition?.victory ? `Current mission: ${operation.name}` : p.status === 'completed' ? 'Current camp task complete' : p.status === 'cancelled' ? 'Project canceled' : `Current task: build the ${p.name}`}</strong><p>{operation && !expedition?.victory ? `${operation.phaseName}, phase ${operation.phase} of 3. ${planName(operation.plan)}. Scout, escort supplies and prepare the line together.` : p.status === 'completed' ? `The ${p.name} is complete. Check Operations for the next advance.` : p.status === 'cancelled' ? 'Unconsumed funding has been refunded. The company’s work remains in its campaign record.' : `Gather ${p.requirements.materials} Materials and complete ${p.requirements.work} Work together. Free orders can cover the entire project.`}</p><button className="qm-text-button" onClick={() => setLocalView(operation ? 'operation' : 'help')}>{operation ? 'Open current mission' : 'Read How to Play'} <FiArrowRight /></button></aside></section>
    <nav className="lc-navigation" aria-label="Campaign views">{([['map', 'War Map'], ...(expedition ? [['operation', 'Operations']] as const : []), ['camp', 'Our Camp'], ['service', 'My Service'], ['dispatches', 'Dispatches'], ['help', 'How to Play']] as const).map(([id, label]) => <button key={id} aria-current={localView === id ? 'page' : undefined} onClick={() => setLocalView(id)}>{label}</button>)}<span>{expedition ? "WIP · More encounters, world detail and cosmetics still to come" : "Map gameplay & ballots: work in progress"}</span></nav>
    {liveMessage && <div key={liveMessage.id} className={`lc-live-action lc-action-${liveMessage.kind}`} role="status"><span className="lc-action-sigil" aria-hidden="true"><FiFlag /></span><div><small>Just happened in our campaign</small><strong>{liveMessage.label}</strong></div><i aria-hidden="true" /></div>}
    {(notice || pending) && <div className={`lc-notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}><p>{notice || 'A saved request is pending confirmation.'}</p>{pending && !busy && <button className="qm-button gold" onClick={() => void execute(pending)}>Reconcile saved request</button>}</div>}
    {m.frozen && <p role="alert" className="lc-notice error">Your account is frozen. Orders and contributions are unavailable.</p>}
    {localView === 'map' && <CampaignMap completedKitchen={p.status === 'completed' || Boolean(expedition?.facilities.some(f => f.blueprint === 'kitchen'))} startedKitchen={p.materials > 0 || p.work > 0} openCamp={() => setLocalView('camp')} expedition={expedition} actionPanel={mapActions} activity={expedition?.activity} motion={motion} openOperation={() => setLocalView('operation')} />}
    {localView === 'operation' && <CampaignOperations state={state} disabled={disabled} hasQuote={Boolean(quote)} command={command} review={(kind, job, targetId, quantity) => void review(kind, job, targetId, quantity)} />}
    {localView === 'help' && <CampaignHowTo state={state} openCamp={() => setLocalView('camp')} />}
    {quote && <div className="lc-quote" ref={quotePanel} tabIndex={-1} aria-label="Review campaign quote"><p className="qm-eyebrow">Confirm the useful result</p><h3>{quote.targetName}</h3><p><strong>+{quote.units} {quote.kind === 'order' ? quote.resource : quote.kind === 'supplies' ? 'Supplies' : 'Materials'}</strong> for <strong>{quote.kind === 'order' ? '1 free order' : `${quote.cost} Shillings`}</strong>.</p>{quote.kind !== 'order' && <><dl><div><dt>Available balance after</dt><dd>{quote.balanceAfter} Shillings</dd></div><div><dt>Remaining target need</dt><dd>{quote.remainingNeed} {quote.kind === 'supplies' ? 'Supplies' : 'Materials'}</dd></div><div><dt>Remaining paid capacity</dt><dd>{quote.remainingPaidCapacity} {quote.kind === 'supplies' ? 'Supplies' : 'Materials'}</dd></div><div><dt>Remaining daily allowance</dt><dd>{quote.remainingDailyAllowance} Shillings</dd></div></dl><p>Committed to {quote.targetName}. Consumed on completion, refunded if canceled unfinished. Facility benefits last for this campaign.</p></>}<p>Quote expires {date(quote.expiresAt)}. A changed target requires a fresh quote.</p><div className="lc-buttons"><button className="qm-button gold" disabled={disabled} onClick={() => command(quote.kind === 'order' ? 'order' : 'contribute', { quoteId: quote.id })}>Confirm {quote.kind === 'order' ? 'free order' : `${quote.cost} Shillings`} <FiCheck /></button><button className="qm-button" disabled={busy || Boolean(pending)} onClick={() => setQuote(null)}>Keep reviewing</button></div></div>}
    {localView === 'camp' && <><div className="lc-layout"><article className="lc-objective"><div className="lc-objective-top"><p className="qm-eyebrow">Shared camp project</p><span className={`lc-status ${p.status}`}>{status}</span></div><CampScene name={p.name} complete={p.status === 'completed'} started={p.materials > 0 || p.work > 0} /><div className="lc-objective-body"><h3>{p.status === 'completed' ? p.name : `Build the ${p.name}`}</h3><p>A dependable camp keeps the expedition moving. Complete both tracks to finish this shared facility.</p><div className="lc-progress-grid">{([['Materials', p.materials, p.requirements.materials], ['Construction Work', p.work, p.requirements.work]] as const).map(([label, value, maximum]) => <div className="lc-progress" key={label}><div><label htmlFor={`lc-${label.replaceAll(' ', '-')}`}>{label}</label><strong>{value}<small> / {maximum}</small></strong></div><progress id={`lc-${label.replaceAll(' ', '-')}`} value={value} max={maximum} /><small>{label === 'Materials' ? `${p.materials - p.paidMaterials} gathered free · ${p.paidMaterials} funded` : 'Every unit comes from a free Build order'}</small></div>)}</div><div className="lc-benefit"><FiFlag /><div><strong>{p.benefitActive ? `${p.name} complete` : 'What we are building toward'}</strong><p>{p.name === 'Engineer Workshop' ? 'Gather output rises from 10 to 12 Materials.' : p.name === 'Signal Post' ? 'Scout output rises from 2 to 3 Recon.' : 'Escort output rises from 4 to 5 Supplies.'} Shared equally, beginning in the cycle after completion.</p></div></div><div className="lc-cycle"><FiClock /><p>{p.status === 'active' ? `Next resolution: ${date(c.nextAt)}.` : `Current campaign day: ${c.cycle}.`}<small>{c.cutoff} {c.timezone}. Incomplete progress stays. Goal frozen for {p.population} expected members.</small></p></div></div></article>
    <aside className="lc-actions"><section className="lc-orders"><p className="qm-eyebrow">Help for free</p><div className="lc-order-count"><h3>Your orders</h3><strong>{m.orders}<small> / 6</small></strong></div><p>3 orders each campaign day. Bank up to 6. No streak to maintain.</p>{!m.joined ? <button className="qm-button gold" disabled={disabled} onClick={() => command('join')}>Join the shared campaign <FiArrowRight /></button> : <><button className="lc-job" disabled={!actionable || !m.orders || p.materials >= p.requirements.materials || Boolean(quote)} onClick={() => void review('order', 'gather')}><FiPackage /><span><strong>Engineer: Gather</strong><small>Review up to {Math.min(expedition?.facilities.some(f => f.blueprint === 'workshop' && f.benefitActive) ? 12 : 10, p.requirements.materials - p.materials)} useful Materials</small></span><b>1 order</b></button><button className="lc-job" disabled={!actionable || !m.orders || p.work >= p.requirements.work || Boolean(quote)} onClick={() => void review('order', 'build')}><FiTool /><span><strong>Engineer: Build</strong><small>Review +1 Construction Work</small></span><b>1 order</b></button></>}<p className="lc-free-note">This entire project can be completed without spending Shillings.</p></section>
    <section className="lc-funding"><p className="qm-eyebrow">Optional support</p><h3>Sponsor materials</h3><p>1 Shilling provides 1 Material. All construction work stays free.</p><label htmlFor="lc-amount">Materials to contribute</label><div className="lc-amount-row"><input id="lc-amount" type="number" min="1" max="30" step="1" value={amount} disabled={!actionable} onChange={event => setAmount(event.target.value)} /><span>Shillings</span></div><div className="lc-presets">{[5, 10, 25].map(value => <button key={value} aria-pressed={amount === String(value)} disabled={!actionable} onClick={() => setAmount(String(value))}>{value}</button>)}</div><button className="qm-button" disabled={!actionable || Boolean(quote) || !/^[1-9]\d*$/.test(amount) || !Number.isSafeInteger(Number(amount)) || Number(amount) > 30} onClick={() => void review('materials')}>Review contribution <FiArrowRight /></button><dl><div><dt>Your available purse</dt><dd>{m.availableBalance}</dd></div><div><dt>Your accepted today</dt><dd>{m.acceptedToday} / {m.dailyCap}</dd></div><div><dt>Funded share of target</dt><dd>{p.paidMaterials} / {p.paidCap}</dd></div></dl><small>The daily ceiling is a limit, never a spending target. Pay Chest savings are never withdrawn automatically.</small></section></aside></div>
    {m.canModerate && <details className="lc-moderation"><summary>Restricted project controls</summary><p>Canceling refunds every unconsumed commitment to its original owner. Free work stays recorded. Completed facilities cannot be canceled.</p><label>Reason<input value={reason} maxLength={200} onChange={event => setReason(event.target.value)} /></label><button className="qm-button" disabled={disabled || p.status !== 'active' || reason.trim().length < 3} onClick={() => { if (window.confirm('Cancel this unfinished camp project and refund its committed Shillings?')) command('cancel', { targetId: p.id, reason }); }}>Cancel and refund</button></details>}</>}
    {localView === 'service' && <section className="lc-records"><p className="qm-eyebrow">Your private campaign record</p><h3>{m.campaignOrders} useful campaign orders</h3><p>Campaign game records are separate from personnel medals and ranks. Showcase cosmetics arrive in Milestone 3.</p><h4>Contribution receipts</h4>{m.receipts.length ? m.receipts.slice().reverse().map(receipt => <article className="lc-receipt" key={receipt.id}><div><strong>{receipt.targetName}</strong><span className="lc-status">{receipt.status}</span></div><p>{receipt.amount} Shillings · {receipt.units} {receipt.resource ?? 'materials'} · {date(receipt.at)}</p><small>Original ledger receipt #{receipt.ledgerId}{receipt.refundLedgerId ? ` · Refund ledger receipt #${receipt.refundLedgerId}` : ''} · Campaign day {receipt.cycle}</small></article>) : <p>No contributions yet. Free orders are always a complete participation path.</p>}<h4>Useful orders</h4>{m.ordersHistory.length ? m.ordersHistory.map(order => <p key={order.id}>{order.job}: +{order.units} {order.resource} · {date(order.at)}</p>) : <p>No useful orders recorded yet. Join the camp and review a Gather or Build order.</p>}</section>}
    {localView === 'dispatches' && <section className="lc-records"><p className="qm-eyebrow">From the shared camp</p><h3>Campaign dispatches</h3>{state.activity.length ? state.activity.map(entry => <article className="lc-receipt" key={entry.id}><p>{entry.text}</p><time dateTime={entry.at}>{date(entry.at)}</time></article>) : <p>No resolution yet. Reports appear when the company resolves an encounter, completes a phase or facility, or cancels a target.</p>}</section>}
    <footer className="lc-footer"><span>SECOND TO NONE</span><small>Standalone cooperative campaign · {expedition ? 'Expedition rules v0.4' : 'Pilot rules v0.3'}</small></footer>
  </section>;
}
