import { useState, type ReactNode } from 'react';
import { FiArrowRight, FiClock, FiCrosshair, FiFlag, FiShield, FiUsers, FiCreditCard, FiAward } from 'react-icons/fi';
import { CoinReward } from './QuartermasterRewards';
import { shillings, type ActionArgs, type ActionKey, type QuartermasterSnapshot } from '../lib/quartermaster';
import type { Reward, RewardLocation } from '../lib/quartermasterMotion';

function left(value:string|null|undefined,now:number) {
 const seconds=Math.max(0,Math.ceil((new Date(value||0).getTime()-now)/1000));
 if(!seconds)return '';
 const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);
 return days?`${days}d ${hours}h`:hours?`${hours}h ${minutes}m`:minutes?`${minutes}m ${seconds%60}s`:`${seconds}s`;
}
const categories=[{id:'tables',title:'Cards & dice',detail:'Blackjack and Lucky Dice',icon:<FiCreditCard/>},{id:'friends',title:'With friends',detail:'Duels and Split or Steal',icon:<FiUsers/>},{id:'ventures',title:'Raids & schemes',detail:'Heists, crime and counters',icon:<FiFlag/>},{id:'lottery',title:'Weekly lottery',detail:'Sunday at 8 PM Chicago',icon:<FiAward/>}] as const;
type Props={snapshot:QuartermasterSnapshot;locked:boolean;now:number;rewards:Partial<Record<RewardLocation,Reward>>;run:(action:ActionKey,args?:ActionArgs)=>Promise<boolean>;status:(action:ActionKey)=>ReactNode;tables:ReactNode};
export default function QuartermasterSocial({snapshot,locked,now,rewards,run,status,tables}:Props) {
 const {profile:me,social,config:c}=snapshot;
 const [category,setCategory]=useState<string>('tables');
 const [duelTarget,setDuelTarget]=useState(''),[duelStake,setDuelStake]=useState('10');
 const [splitTarget,setSplitTarget]=useState(''),[splitChoice,setSplitChoice]=useState<'split'|'steal'>('split');
 const [tickets,setTickets]=useState(1);
 const peers=snapshot.leaderboard.filter(member=>member.discordId!==me.discordId);
 const duel=social.duels.find(game=>game.status==='open'),split=social.splitGames.find(game=>game.status==='open');
 const latestDuel=social.duels.find(game=>game.status!=='open'),latestSplit=social.splitGames.find(game=>game.status!=='open');
 const heist=social.heist, heistRules=heist?.rules??c.heist, lottery=social.lottery;
 const crew=heist?.participants??[],inHeist=crew.some(member=>member.discordId===me.discordId);
 const recruiting=heist?.status==='open',heistWait=left(heist?.expiresAt,now),cooldown=left(snapshot.cooldowns.heist,now);
 const crimeWait=left(snapshot.cooldowns.crime,now),forageWait=left(snapshot.cooldowns.steal,now);
 const availableTickets=Math.max(0,c.lottery.max_tickets_per_member-(lottery?.ownTickets??0));
 const ticketValid=Number.isInteger(tickets)&&tickets>0&&tickets<=availableTickets&&tickets*c.lottery.ticket_price<=me.purse;
 const dailyFree=social.splitFreeAvailable!==false;
 const result=(key:ActionKey)=><><CoinReward reward={rewards[key as RewardLocation]}/>{status(key)}</>;
 return <section className="qm-games-room">
   <header className="qm-games-welcome"><div><p className="qm-eyebrow">After the day's duty</p><h2>The company mess.</h2><p>A seat at the tables. A wager with a friend. A wagon worth the risk.</p><span className="qm-tag">Fictional Shillings · no cash value</span></div><img src={`${import.meta.env.BASE_URL}quartermaster/quartermaster-games-table-v1.webp`} alt="" width="1200" height="800"/><div className="qm-room-wallet"><small>Your Wallet</small><strong>{me.purse.toLocaleString()}</strong><span>Shillings available</span></div></header>
   <nav className="qm-game-categories" aria-label="Game categories">{categories.map(item=><button key={item.id} aria-pressed={category===item.id} className={category===item.id?'active':''} onClick={()=>setCategory(item.id)}>{item.icon}<span><strong>{item.title}</strong><small>{item.detail}</small></span>{item.id==='friends'&&(duel||split)&&<i aria-label="Open invitation"/>}</button>)}</nav>
   <div className="qm-game-category-content" key={category} aria-busy={locked}>
   {category==='tables'&&tables}
   {category==='friends'&&<div className="qm-social-grid">
     <section className="qm-panel qm-social-card wide qm-split-table"><p className="qm-eyebrow">Two people. Two sealed choices.</p><h3>Split or Steal</h3><div className="qm-pot-display"><span>The daily pot</span><strong>{split?.rewardPot??c.splitsteal.reward_pot??50}</strong><small>Shillings · free to play</small></div><div className="qm-split-rules"><span>Both split <b>25 each</b></span><span>One steals <b>50 to the thief</b></span><span>Both steal <b>Neither is paid</b></span></div>
       {split?.targetId===me.discordId?<div className="qm-social-callout"><strong>{split.challengerName} has sealed their choice.</strong><span>Choose before {left(split.expiresAt,now)||'the invitation expires'}. The choice is revealed after you answer.</span><div><button className="qm-button gold" disabled={locked} onClick={()=>void run('splitsteal',{action:'choose',gameId:split.id,choice:'split'})}>Split the pot</button><button className="qm-button danger" disabled={locked} onClick={()=>void run('splitsteal',{action:'choose',gameId:split.id,choice:'steal'})}>Steal the pot</button><button className="qm-text-button" disabled={locked} onClick={()=>void run('splitsteal',{action:'decline',gameId:split.id})}>Decline</button></div></div>:split?<div className="qm-social-callout"><strong>Choice sealed. Waiting for {split.targetName}.</strong><span>{left(split.expiresAt,now)||'Settling invitation…'}</span></div>:!dailyFree?<p className="qm-social-callout">You have played your free game today. A new pot is available after midnight Chicago time.</p>:<form className="qm-social-form" onSubmit={e=>{e.preventDefault();void run('splitsteal',{action:'challenge',targetDiscordId:splitTarget,choice:splitChoice});}}><label className="qm-field">Invite a friend<select value={splitTarget} onChange={e=>setSplitTarget(e.target.value)}><option value="">Choose a member</option>{peers.map(p=><option value={p.discordId} key={p.discordId}>{p.displayName}</option>)}</select></label><div className="qm-choice" role="group" aria-label="Your secret choice"><button type="button" aria-pressed={splitChoice==='split'} className={splitChoice==='split'?'active':''} onClick={()=>setSplitChoice('split')}>Split</button><button type="button" aria-pressed={splitChoice==='steal'} className={splitChoice==='steal'?'active danger':''} onClick={()=>setSplitChoice('steal')}>Steal</button></div><button className="qm-button gold" disabled={locked||!splitTarget}>Seal choice & invite<FiArrowRight/></button></form>}
       {latestSplit?.result&&<p className="qm-social-result" key={latestSplit.id}>{latestSplit.result}</p>}{result('splitsteal')}<p className="qm-help">One completed free game per member per Chicago day. Declined or expired invitations do not use your daily game.</p>
     </section>
     <section className="qm-panel qm-social-card"><span className="qm-social-icon"><FiCrosshair/></span><p className="qm-eyebrow">Equal stakes. Even odds.</p><h3>A gentleman's duel</h3><p>Both members stake the same amount. One wins the full pot. A 50% chance each.</p>{duel?.targetId===me.discordId?<div className="qm-social-callout"><strong>{duel.challengerName} challenges you for {shillings(duel.stake)}.</strong><span>{left(duel.expiresAt,now)||'Challenge expiring…'}</span><button className="qm-button gold" disabled={locked||me.purse<duel.stake} onClick={()=>void run('duel',{action:'accept',gameId:duel.id})}>Accept duel</button><button className="qm-button" disabled={locked} onClick={()=>void run('duel',{action:'decline',gameId:duel.id})}>Decline</button></div>:duel?<p className="qm-social-callout">Waiting for {duel.targetName}. {shillings(duel.stake)} held until the challenge is answered or expires.</p>:<form className="qm-social-form" onSubmit={e=>{e.preventDefault();void run('duel',{action:'challenge',targetDiscordId:duelTarget,stake:Number(duelStake)});}}><label className="qm-field">Choose your opponent<select value={duelTarget} onChange={e=>setDuelTarget(e.target.value)}><option value="">Select a member</option>{peers.map(p=><option key={p.discordId} value={p.discordId}>{p.displayName}</option>)}</select></label><label className="qm-field">Each member stakes<input type="number" min={c.duel.min_stake} max={c.duel.max_stake} value={duelStake} onChange={e=>setDuelStake(e.target.value)}/></label><button className="qm-button gold" disabled={locked||!duelTarget||!Number.isInteger(Number(duelStake))||Number(duelStake)<c.duel.min_stake||Number(duelStake)>Math.min(me.purse,c.duel.max_stake)}>Issue challenge</button></form>}{latestDuel&&<p className="qm-social-result">{latestDuel.winnerName?`${latestDuel.winnerName} won ${shillings(latestDuel.stake*2)}.`:`Last challenge ${latestDuel.status}.`}</p>}{result('duel')}</section>
   </div>}
   {category==='ventures'&&<div className="qm-social-grid">
     <section className="qm-panel qm-social-card wide qm-heist"><span className="qm-social-icon"><FiFlag/></span><p className="qm-eyebrow">The supply road</p><h3>A wagon worth taking.</h3><p>Recruit a crew. One shared outcome. The whole team succeeds or the whole team is caught.</p><div className="qm-heist-facts"><span>Entry<strong>{heistRules.entry_fee} Shillings</strong></span><span>Success<strong>{Math.round(heistRules.success_chance*100)}%</strong></span><span>Returned per member<strong>{heistRules.payout_min}–{heistRules.payout_max}</strong></span><span>Extra fine on failure<strong>Up to {heistRules.fine_max}</strong></span></div>
       {recruiting?<><div className="qm-social-timer"><FiClock/>{heistWait?`Crew departs in ${heistWait}`:'Departure reached. Waiting for the server result…'}</div><div className="qm-crew">{crew.map(member=><span key={member.discordId}><FiUsers/>{member.displayName}</span>)}</div><p>{crew.length}/{heistRules.max_players} crew · at least {heistRules.min_players} needed</p><button className="qm-button gold" disabled={locked||inHeist||!heistWait||Boolean(cooldown)||me.purse<heistRules.entry_fee} onClick={()=>void run('heist',{action:'join',gameId:heist!.id})}>{inHeist?'You are on the crew':`Join for ${heistRules.entry_fee} Shillings`}</button></>:<><p>Recruiting stays open for {c.heist.lobby_seconds} seconds. If fewer than two members join, entries are returned.</p><button className="qm-button gold" disabled={locked||Boolean(cooldown)||me.purse<c.heist.entry_fee} onClick={()=>void run('heist',{action:'start'})}>{cooldown?`Next heist in ${cooldown}`:`Recruit a crew · ${c.heist.entry_fee} Shillings`}</button>{heist?.result&&<p className="qm-social-result">{heist.result}</p>}</>}{result('heist')}<p className="qm-help">Failure loses your entry and has a 50% chance of an extra {c.heist.fine_min}–{c.heist.fine_max} Shilling fine, capped by your remaining Wallet. Your Pay Chest stays safe. One-hour cooldown.</p></section>
     <section className="qm-panel qm-social-card"><span className="qm-social-icon"><FiCrosshair/></span><p className="qm-eyebrow">A risky errand</p><h3>Crime</h3><p>{Math.round(c.crime.success_chance*100)}% chance to earn {c.crime.payout_min}–{c.crime.payout_max} Shillings. Get caught and pay {c.crime.fine_min}–{c.crime.fine_max}, capped by your Wallet.</p><button className="qm-button gold" disabled={locked||Boolean(crimeWait)} onClick={()=>void run('crime')}>{crimeWait?`Ready in ${crimeWait}`:'Try the errand'}</button>{result('crime')}</section>
     <section className="qm-panel qm-social-card"><span className="qm-social-icon"><FiShield/></span><p className="qm-eyebrow">Settle a recent score</p><h3>Counter-steal</h3>{social.counterAvailable?<><p>{social.counterAvailable.attackerName} took {shillings(social.counterAvailable.taken)}. You have a {Math.round(c.countersteal.success_chance*100)}% chance to recover half.</p><button className="qm-button" disabled={locked||Boolean(forageWait)} onClick={()=>void run('countersteal')}>{forageWait?`Ready in ${forageWait}`:'Follow the trail'}</button></>:<p>No recent successful forage to counter. A fresh opportunity lasts {c.countersteal.window_seconds/60} minutes.</p>}{result('countersteal')}</section>
     <section className="qm-panel qm-social-card wanted"><p className="qm-eyebrow">The company watch list</p><h3>Most Wanted</h3><ol>{[...snapshot.leaderboard].sort((a,b)=>b.forageWins-a.forageWins||a.displayName.localeCompare(b.displayName)).slice(0,10).map(member=><li key={member.discordId}><span>{member.displayName}</span><strong>{member.forageWins} successful forages</strong></li>)}</ol></section>
   </div>}
   {category==='lottery'&&<section className="qm-panel qm-lottery-room"><div><p className="qm-eyebrow">The Sunday draw</p><h3>The company lottery.</h3><p>Every ticket adds {shillings(c.lottery.ticket_price)} to the pot. One winning ticket takes it all.</p><div className="qm-pot-display"><span>Current pot</span><strong>{lottery?.pot??c.lottery.starting_pot}</strong><small>Shillings · starts at {c.lottery.starting_pot}</small></div></div><div className="qm-lottery-ticket"><p className="qm-eyebrow">Your entry</p><h3>{lottery?.ownTickets??0} / {c.lottery.max_tickets_per_member} tickets</h3><p>{lottery?.entrants??0} members · {lottery?.totalTickets??0} tickets entered</p><form onSubmit={e=>{e.preventDefault();void run('lottery',{action:'buy',qty:tickets});}}><label className="qm-field">Tickets to buy<input type="number" min="1" max={Math.max(1,availableTickets)} value={tickets} onChange={e=>setTickets(Number(e.target.value))} disabled={!availableTickets}/></label><button className="qm-button gold" disabled={locked||!ticketValid}>{availableTickets?`Buy for ${shillings(tickets*c.lottery.ticket_price)}`:'All three tickets purchased'}</button></form>{result('lottery')}<div className="qm-social-timer"><FiClock/>{left(lottery?.drawsAt,now)||'The next draw is being prepared'}</div><p>Sunday, 8 PM Chicago time. At least two different members must enter; otherwise the same tickets and pot carry forward.</p>{lottery?.rolloverReason&&<p className="qm-social-result">{lottery.rolloverReason}</p>}{lottery?.lastResult?.winnerName&&<p className="qm-social-result">Previous draw: {lottery.lastResult.winnerName} won {shillings(lottery.lastResult.pot)}.</p>}</div></section>}
   </div>
   <p className="qm-social-footnote">Results come from the shared server. Open games update every five seconds. Play when you fancy it; your balance and collection stay with you.</p>
 </section>;
}

